require('dotenv').config();
const port = process.env.PORT;
const express = require('express');
const path = require('path');
const app = express();

if (process.env.NODE_ENV !== 'production') {
	const webpack = require('webpack');
	const webpackDevMiddleware = require('webpack-dev-middleware');
	const webpackHotMiddleware = require('webpack-hot-middleware');
	const config = require('./webpack.dev.js');
	const compiler = webpack(config);
	app.use(webpackHotMiddleware(compiler));
	app.use(webpackDevMiddleware(compiler, {
		noInfo: true,
		publicPath: config.output.publicPath,
	}));
}

// serve bundled file generated by webpack
app.use(express.static(path.join(__dirname, './dist')));

app.get('/*', (req, res) => {
	const html = `
      <!doctype html>
      <html>
          <head>
          </head>
          <body>
            <div id="root"></div>
            <script src="/app.bundle.js"></script>
          </body>
      </html>
  `;
	res.send(html);
});

app.listen(port, () => {
	console.log('Started listening on port', port);
});